[workspace]

members = [
    "smart_contracts/contract",
    "smart_contracts/contracts/[!.]*/*",
    "grpc/server",
    "grpc/test_support",
    "grpc/tests",
    "types",
    "node",
    "client",
]

default-members = [
    "smart_contracts/contract",
    "grpc/server",
    "grpc/test_support",
    "grpc/tests",
    "types",
    "node",
    "client",
]

# Include debug symbols in the release build of `casperlabs-engine-tests` so that `simple-transfer` will yield useful
# perf data.
[profile.release.package.casperlabs-engine-tests]
debug = true

[profile.release]
# TODO: nightly compiler has issues with linking libraries with LTO enabled.
# Change this back to true once stable is supported by default.
lto = false

[profile.bench]
lto = true
