[package]
name = "host-function-metrics"
version = "0.1.0"
authors = ["Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
bench = false
doctest = false
test = false

[features]
default = ["contract/test-support", "rand/small_rng"]
std = ["contract/std", "types/std"]

[dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract" }
types = { path = "../../../../types", package = "casperlabs-types" }
rand = { version = "0.7", default-features = false }
