[package]
name = "add-associated-key"
version = "0.1.0"
authors = ["Joe Sacher <joes@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "add_associated_key"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["contract/std", "types/std"]

[dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract" }
types = { path = "../../../../types", package = "casperlabs-types" }
