[package]
name = "casperlabs-node"
version = "0.1.0"
authors = ["Marc Brinkmann <marc@casperlabs.io>", "Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2018"
description = "The CasperLabs blockchain node"
documentation = "https://docs.rs/casperlabs-node"
readme = "README.md"
homepage = "https://casperlabs.io"
repository = "https://github.com/CasperLabs/casperlabs-node"
license-file = "LICENSE"
publish = false  # Prevent accidental `cargo publish` for now.
default-run = "casperlabs-node"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.28"
base16 = "0.2.1"
bincode = "1.2.1"
blake2 = { version = "0.8.1", default-features = false }
bytes = "0.5.4"
derive_more = "0.99.7"
directories = "2.0.2"
ed25519-dalek = { version = "1.0.0-pre.3", default-features = false, features = ["rand", "serde", "u64_backend"] }
either = "1.5.3"
enum-iterator = "0.6.0"
thiserror = "1.0.18"
futures = "0.3.5"
getrandom = "0.1.14"
hex = "0.4.2"
hex_fmt = "0.3.0"
http = "0.2.1"
itertools = "0.8.2"
lazy_static = "1.4.0"
linked-hash-map = "0.5.2"
lmdb = "0.8.0"
maplit = "1.0.2"
num-derive = "0.3.0"
num-traits = "0.2.10"
openssl = "0.10.29"
parity-wasm = "0.41.0"
pwasm-utils = "0.12.0"
rand = "0.7.3"
rand_chacha = "0.2.2"
reqwest = "0.10.6"
rmp-serde = "0.14.3"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.55"
serde-big-array = "0.3.0"
smallvec = "1.4.0"
structopt = "0.3.14"
tempfile = "3.1.0"
tokio = { version = "0.2.20", features = ["macros", "rt-threaded", "sync", "tcp", "time", "blocking"] }
tokio-openssl = "0.4.0"
tokio-serde = { version = "0.6.1", features = ["messagepack"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
toml = "0.5.6"
tracing = "0.1.14"
tracing-subscriber = "0.2.5"
warp = "0.2.3"
wasmi = "0.6.2"
types = { path = "../types", package = "casperlabs-types", features = ["std", "gens"] }
chrono = "0.4.10"
hostname = "0.3.0"
libc = "0.2.66"
log = { version = "0.4.8", features = ["std", "serde", "kv_unstable"] }
num = { version = "0.2.0", default-features = false }
proptest = { version = "0.9.4", optional = true }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
wabt = "0.9.2"

###
parking_lot = "0.10.0"

[features]
vendored-openssl = ['openssl/vendored']
test-support = []
no-unstable-features = [
    "types/no-unstable-features",
]
gens = ["proptest"]

[[bin]]
name = "casperlabs-node"
path = "src/apps/node/main.rs"
bench = false
doctest = false
test = false

[[bin]]
name = "casperlabs-client"
path = "src/apps/client/main.rs"
bench = false
doctest = false
test = false

[package.metadata.deb]
features = ["vendored-openssl"]
assets = [
    ["./target/release/casperlabs-node","/usr/bin/casperlabs-node", "755"],
    ["./target/release/casperlabs-client","/usr/bin/casperlabs-client", "755"]
]

[dev-dependencies]
assert_matches = "1.3.0"
lazy_static = "1"
pnet = "0.26.0"
proptest = "0.9.4"
rand_core = "0.5.1"
rand_xorshift = { version = "~0.2.0" }
fake_instant = "0.4.0"