[package]
name = "named-purse-payment"
version = "0.1.0"
authors = ["Ed Hastings <ed@gmail.com>"]
edition = "2018"

[[bin]]
name = "named_purse_payment"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
std = ["contract/std", "types/std"]

[dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract" }
types = { path = "../../../../types", package = "casperlabs-types" }
