[package]
name = "unbonding"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "unbonding"
bench = false
doctest = false
test = false

[features]
std = ["contract/std", "types/std"]

[dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract" }
types = { path = "../../../../types", package = "casperlabs-types" }
