[package]
name = "create-test-node-shared"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>"]
edition = "2018"

[features]
std = ["base16/std", "contract/std"]

[dependencies]
base16 = { version = "0.2.1", default-features = false }
contract = { path = "../../../contract", package = "casperlabs-contract" }
types = { path = "../../../../types", package = "casperlabs-types" }
